apiVersion: v1
kind: Service
metadata:
  name: bye
  labels:
    app: bye
    service: bye
spec:
  selector:
    app: bye
    service: bye
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP